import type { Property, Testimonial, StatItem } from './types'

export const properties: Property[] = [
  {
    id: '1',
    title: 'Concepción Arenal 3505 2ºA',
    address: 'Concepción Arenal 3505 2ºA',
    neighborhood: 'Colegiales',
    city: 'CABA',
    operation: 'Venta',
    currency: 'ARS',
    price: 650000,
    priceLabel: '$650.000',
    bedrooms: 1,
    bathrooms: 1,
    garage: false,
    surface: 40,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=75',
    slug: 'concepcion-arenal-3505',
  },
  {
    id: '2',
    title: 'Altolaguirre 1321',
    address: 'Altolaguirre 1321',
    neighborhood: 'Merlo',
    city: 'GBA Oeste',
    operation: 'Venta',
    currency: 'USD',
    price: 48000,
    priceLabel: 'USD 48.000',
    bedrooms: 2,
    bathrooms: 1,
    garage: true,
    surface: 72,
    image: 'https://images.unsplash.com/photo-1567767292278-a8ec40652a98?w=600&q=75',
    slug: 'altolaguirre-1321',
  },
  {
    id: '3',
    title: 'Tamborini 3768 2A',
    address: 'Tamborini 3768 2A',
    neighborhood: 'Villa Urquiza',
    city: 'CABA',
    operation: 'Venta',
    currency: 'USD',
    price: 92000,
    priceLabel: 'USD 92.000',
    bedrooms: 1,
    bathrooms: 1,
    garage: true,
    surface: 29,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=75',
    slug: 'tamborini-3768',
  },
  {
    id: '4',
    title: 'Padilla 736',
    address: 'Padilla 736',
    neighborhood: 'Villa Crespo',
    city: 'CABA',
    operation: 'Venta',
    currency: 'USD',
    price: 17000,
    priceLabel: 'USD 17.000',
    garage: true,
    surface: 12.5,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=75',
    slug: 'padilla-736',
  },
  {
    id: '5',
    title: 'Juan M. Gutiérrez 3771 P2 D17',
    address: 'Juan M. Gutiérrez 3771 P2 D17',
    neighborhood: 'Palermo',
    city: 'CABA',
    operation: 'Venta',
    currency: 'USD',
    price: 410000,
    priceLabel: 'USD 410.000',
    bedrooms: 1,
    bathrooms: 1,
    garage: true,
    surface: 73,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=75',
    slug: 'gutierrez-3771',
  },
  {
    id: '6',
    title: 'Av. Maipú 1901 8ºC',
    address: 'Av. Maipú 1901 8ºC',
    neighborhood: 'Vicente López',
    city: 'GBA Norte',
    operation: 'Alquiler',
    currency: 'USD',
    price: 1000,
    priceLabel: 'USD 1.000/mes',
    bedrooms: 2,
    bathrooms: 1,
    garage: false,
    surface: 70,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=75',
    slug: 'maipu-1901',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Yair DiazRoy Bennett',
    text: 'Me asesoraron en todas mis consultas sobre una propiedad; muy buen servicio.',
    source: 'Google',
    rating: 5,
  },
  {
    id: '2',
    name: 'Julia Degreef',
    text: 'Tengo el placer de elegir a Lexinton Propiedades por su excelente asesoramiento durante mi experiencia de compra/venta de un departamento. Los agentes inmobiliarios fueron profesionales, eficientes y siempre estuvieron dispuestos a responder todas mis preguntas.',
    source: 'Google',
    rating: 5,
  },
  {
    id: '3',
    name: 'Celeste Cruz Romero',
    text: 'Altamente confiables. Agradezco enormemente su responsabilidad y la atención detallada en cada etapa del proceso. ¡Excelente trabajo!',
    source: 'Google',
    rating: 5,
  },
]

export const stats: StatItem[] = [
  { value: '20', label: 'años de trayectoria' },
  { value: '5.000+', label: 'clientes satisfechos' },
  { value: 'N°1', label: 'en operaciones simultáneas' },
]

export const neighborhoods = [
  'Belgrano',
  'Colegiales',
  'Núñez',
  'Palermo',
  'Recoleta',
  'Saavedra',
  'Villa Crespo',
  'Villa Urquiza',
  'Vicente López',
  'San Isidro',
  'Tigre',
  'San Fernando',
  'Pilar',
  'Merlo',
  'Zona Norte GBA',
  'Zona Oeste GBA',
  'Zona Sur GBA',
] as const

export const propertyTypes = [
  'Departamento',
  'Casa',
  'PH',
  'Local Comercial',
  'Oficina',
  'Terreno',
  'Cochera',
  'Emprendimiento',
] as const
